# Sprint 3: Sprint Journal for Runjini Murthy

---
## DAY 1: Tuesday (Week 1)
### What I Expect to Learn
* I would like to learn how to perform data operations on data in a SQL database.  This includes filtering, adding columns, and performing calculations. 

### Project References
- Analyzing historical menu data from New York Public Library: https://www.kaggle.com/nypl/whats-on-the-menu -- But what questions?
- UFO sightings data (only one table): https://www.kaggle.com/NUFORC/ufo-sightings/data
- Wine data: https://www.kaggle.com/zynicide/wine-reviews/data
- SQL Tutorial: https://data36.com/sql-for-data-analysis-tutorial-beginners/
- For future project? Game of Thrones: https://www.kaggle.com/mylesoneill/game-of-thrones/data

### Project Pitch
- Language/program comparison: Export my OrangeTheory results from the past 6 months to get: count of sessions; sum of splat points; average of heart rate; sum of calories burned; average of calories burned; average attendance per week; where splat points were under 12; max calories burned, min calories burned
- SQL only: Find a large data set from Kaggle to examine patterns/queries in the data set.

### Notes
- Important link not related to sprint: https://help.github.com/articles/syncing-a-fork/
- SQL's primary goal is to manage and structure data.  Its goal is not to perform analysis.  Calculations are sums, but not statistically significant analysis.
- Commands shown in summary content is fairly comprehensive list of commands.
- SQL can subset/filter/choose, and also creates joins to return tables.
- Group by example: Sum revenue by station ID; for me, sum revenue by HHC tower
- Join on: on a specific field
- Union: Combining tables together by pasting rows together
- Into: Putting into temporary tables; to check to see if query is running but the database is too large. Do a limit for top 100 rows and then put them into a temp table.  Then perform manipulation on the temp table.
- From: Use when you have more than one database.
- Command line will probably always be in use.  But SQL GUI editors would also be used on the job.
- Update: Edit a row
- Create Index / Drop Index: Index controls unique IDs; affects efficiency of table - can run much faster.
- For huge data sets, skill is agility in subsetting out data to size you can manage.
- Data dictionary: Explains what each field means. Part of the documenation process for setting up a data.  By a database administrator.
- Vector: List-like object.  However, data types must be homogenous.
- List in R: can have different data types.  A list can store vectors.
- Data frames: Brought in to R through library.  Implements table structure.  Uses lists and vectors.  Constructs lists of columns.
- In interactive environments, these are easily tested.  Project work will allow us to self-experiment.
- Tibbles: Table in R.  Like a variant of data frame.  Updated version of data frame.  Works with packages like Tidyverse.  CRAN includes it.
- In R: observations are rows and variables are columns.
- What are objects in R??
- NAN = not a number
- N/A
- Different libraries treat NANs differently
- In R, "variables" are equivalent to columns
- Nat recommends SQLDBM to visualize data models.

--- 
## DAY 2: Wednesday (Week 1)

### Prototype Notes
- Download data from: https://www.kaggle.com/zynicide/wine-reviews/data
- Count of how many reviews use the word "oak" 
- Counts of wines by country
- Forgot how to import CSVs into SQLite Studio.  The little red questions marks are asking you to name a file, not pull from something existing.  I am sure I will forget again.
- Upload is taking a loooooong time given size of file (130k wine reviews).
- Link to show how to import to R: https://support.rstudio.com/hc/en-us/articles/218611977-Importing-Data-with-RStudio
- Link to show import to SQLite Studio: https://deparkes.co.uk/2016/06/17/sqlite-import-csv/
- Another link: https://digitalfellows.commons.gc.cuny.edu/2016/04/08/fun-times-with-sqlite-or-a-beginners-tutorial-to-data-management-and-databases-with-sql/
- Can you have a primary key ID value equal to 1?
- Link to understand how to perform a "contains" query: https://www.w3schools.com/sql/sql_like.asp  (I needed to put my term in percentage marks: %)
- I think the price column is being read as infinity.  How do I update these values?


### Proposed Plan: Key Milestones by Day

##### Day 2 (Wed Week 1):
- Develop Project Proposal
- Push Docs / Repo / Roadmap Update

##### Day 3 (Thu Week 1):
- Get halfway through Data Camp training for R
- Replicate beginner SQL queries in R
- Look at 2-3 more advanced queries in SQL (union? group by?)
- Determine price max issues -- it appears to be reading as infinity; why?
- Push docs / repo

##### Day 4 (Tue Week 2): 
- Determine all the queries I will be doing in R
- Finish Data Camp training for R
- Bonus: Research beginner queries in Python
- Come up with narrative for presentation & screenshots of tables/code
- Push docs / repo

##### Day 5 (Wed Week 2):
- Project highlights
- Identify question or cohort knowledge gap for sprint review
- Develop Topic Project + Presentation
- Push Repo / docs / Presentation

### Project Definition and README.MD Discussion 
*This is a discussion of how this project will fit into my overall roadmap. I will update my roadmap with the following project definition*

*I will focus my project Repo's README.MD on the same topic, but with this additional detail.*

## SQL Queries
##### How many countries are represented on this list?

`SELECT COUNT(DISTINCT country)
FROM wine_reviews`

Result: 44

##### What is the max points/rating for a given wine?

`SELECT MAX(points)
FROM wine_reviews`

Result: 100

##### What is the minimum points/rating for a given wine?

`SELECT MIN(points)
FROM wine_reviews`

Result: 80

##### How many wines have a perfect score of 100?

`SELECT COUNT(points)
FROM wine_reviews
WHERE points = 100`

Result: 19

##### How many wines have the low score of 80?

`SELECT COUNT(points) 
FROM wine_reviews
WHERE points = 80`

Result: 397

##### What is the average points rating?

`SELECT AVG(points)
FROM wine_reviews`

Result: 88.44713820775404

##### What countries are represented on this list?

`SELECT DISTINCT country
FROM wine_reviews`

Result:
Italy
Portugal
US
Spain
France
Germany
Argentina
Chile
Australia
Austria
South Africa
New Zealand
Israel
Hungary
Greece
Romania
Mexico
Canada

Turkey
Czech Republic
Slovenia
Luxembourg
Croatia
Georgia
Uruguay
England
Lebanon
Serbia
Brazil
Moldova
Morocco
Peru
India
Bulgaria
Cyprus
Armenia
Switzerland
Bosnia and Herzegovina
Ukraine
Slovakia
Macedonia
China
Egypt

##### How many review descriptions contain the words "wood" or "oak"?

`SELECT COUNT(description)
FROM wine_reviews
WHERE description like '%oak%' OR  description like '%wood%'`

Result: 27012

##### Provide all information on wines from India.

`SELECT *
FROM wine_reviews
WHERE country = 'India'`

Result:
(See image)

##### What is the max price of wine on this table?

`SELECT max(price)
FROM wine_reviews
WHERE price IS NOT ("")`

Result:
3300

## R Functions/Instructions

##### What is the sum of points in this table?
Note: This is not a real question I want to ask, but I'm not sure how to filter yet, and I wanted to ask a basic question.

`sum(winemag_data_130k_v2[['points']])`

[1] 11495563


##### What is the mean of points in this table?

`mean(wine[['points']])`

[1] 88.44714

##### What is the mean of points and price for wines priced over 500 dollars in this table?
`wines_over_500 <- subset(wine, price > 500)
mean(wines_over_500)`

`mean(wines_over_500[['points']])`

[1] 95.68132

`mean(wines_over_500[['price']])`

[1] 854.1868

##### What are the unique number of countries represented in the wine table?  What is the count of the unique countries?
`unique((wine[['country']]))`

 [1] "Italy"                  "Portugal"               "US"                     "Spain"                  "France"                
 [6] "Germany"                "Argentina"              "Chile"                  "Australia"              "Austria"               
[11] "South Africa"           "New Zealand"            "Israel"                 "Hungary"                "Greece"                
[16] "Romania"                "Mexico"                 "Canada"                 NA                       "Turkey"                
[21] "Czech Republic"         "Slovenia"               "Luxembourg"             "Croatia"                "Georgia"               
[26] "Uruguay"                "England"                "Lebanon"                "Serbia"                 "Brazil"                
[31] "Moldova"                "Morocco"                "Peru"                   "India"                  "Bulgaria"              
[36] "Cyprus"                 "Armenia"                "Switzerland"            "Bosnia and Herzegovina" "Ukraine"               
[41] "Slovakia"               "Macedonia"              "China"                  "Egypt"                 

`wine_countries <- unique((wine[['country']]))
length(wine_countries)`

[1] 44

##### What is the max price of wine over the value of 1 dollar?
`max(wine[['price']])`

[1] NA

(The first time I tried this, it returned an N/A value.  So, I knew I had to filter.)

`wines_over_1 <- subset(wine, price > 0)
max(wines_over_1[['price']])`

[1] 3300

#####  Instruction to return all the values in the country vector
`winemag_data_130k_v2[['country']]`

#####  Class of column; returns the type of data in this vector; in this case, character
`class(winemag_data_130k_v2[['country']])`

#####  This query is meaningless, but was used as a test.  It asks to sum all the values in the points vector.
`sum(winemag_data_130k_v2[['points']])`

##### Assign a friendlier name to the data frame; in this case, simply call it "wine."
`wine <- winemag_data_130k_v2`

##### Determine the number of unique values in the country column, and then count how many there are.
`wine_countries <- unique((wine[['country']]))
length(wine_countries)`

#####  Determine the number of unique provinces in the table, and then count them.
`wine_provinces <- unique((wine[['province']]))
length(wine_provinces)`

#####  This instruction was meant to determine the maximum price in the table.  However, it returned an "NA" result.
`max(wine[['price']])`

#####  Knowing that there are prices in the field but also some blank/NA values, the code is revised to filter to wines with a value greater than 0, and then determine the maximum.
`wines_over_1 <- subset(wine, price > 0)
max(wines_over_1[['price']])`

#####  Determining the maximum value in the points vector.
`max(wine[['points']])`

#####  Determining the minimum value in the points vector.
`min(wine[['points']])`

#####  Determining how many wines have a rating of 100 points.  Result is 19, which matches the query in SQL.
`wines_rated_100 <- subset(wine, points == 100)
length((wines_rated_100[['points']]))`

#####  Determining how many wines have a rating of 80 points.  Result is 397, which matches the query in SQL.
`wines_rated_80 <- subset(wine, points == 80)
length((wines_rated_80[['points']]))`

##### Determining how many unique countries are represented in the table.  Result is 44, which matches the query in SQL.
`unique((wine[['country']]))
wine_countries <- unique((wine[['country']]))
length(wine_countries)`

#####  Mean point score for table. Result is 88.44714
`mean(wine[['points']])`

##### Determining max price for wines in this table. Because of NA values, need to create a subset where wine price is greater than 1. Result is 3300.
`wines_over_1 <- subset(wine, price > 0)
max(wines_over_1[['price']])`

##### Filtering to show wines from India
`indian_wines <- subset(wine, country == 'India')
View(indian_wines)`

--- 
## DAY 3: Thursday (Week 1)

#### Setup for Repo and Documentation Push
*Setup and testing I did to make sure my repo and documentation were ready to push at the end of the day*

#### Repo File Strategy Discussion
*How I will present my repo files for clarity and demonstration*

#### Data Camp Training in R
1. Finished first two sections of training - basics, vectors. About to start matrices, which should help with table work. 

2. Have a better understanding of vectors; a selection of elements. 

3. Understanding a bit more how you assign variables. 

4. R seems to go through all of your commands before getting to the final answer. 

#### Replicate Beginner SQL Queries in R & Research in R
1. Preliminary Google work to figure out how SQL queries map to R. 
2. Learned that there is a sql package for R: install.packages("sqldf").  Is this cheating? * 
3. Link: http://www.burns-stat.com/translating-r-sql-basics/ *
4. Double vs. integer: I saw col_double() for price and col_integer() for points.  "The two most common numeric classes used in R are integer and double (for double precision floating point numbers). R automatically converts between these two classes when needed for mathematical purposes.  In this case, it makes sense because the points are all integers, whereas the price could have cents, i.e. decimal with two floating digits.  (Source: http://uc-r.github.io/integer_double) 
5. R data frame manipulation: https://www.r-bloggers.com/dataframe-manipulation-in-r-from-basics-to-dplyr/ 
6. Basic sum function in r: https://stackoverflow.com/questions/9676212/how-to-sum-all-values-of-a-column-of-in-a-data-frame 
7. Figured out basic mean and sum functions in R. 
8. Assigned a variable to my data frame name so I didn't have to keep typing it. 
9. Learned about subset instruction/funtion in R - how I can filter values. https://www.statmethods.net/management/subset.html
10. Count unique values in a column in R: https://discuss.analyticsvidhya.com/t/count-number-of-distinct-values-in-a-column-of-a-data-table-in-r/1124
11. Clarifying syntax of "OR" statement in SQL: https://www.w3schools.com/sql/sql_and_or.asp

#### Determine Price Max Issues
1. Worked with Ben to determine how SQL was reading the "blank" price files.  By using operators like = and <, we determined that the value in the field is an empty string, "".  Using boolean queries, we determined that this is read as a value larger than 0.  In order to perform calculations on this column, I needed to modify the query to remove the empty string values.  I could have also updated the values but it would be techncially incorrect to assign it a value like 0.  I might have had to make it a null field.  The most efficient solution was simply to filter out the values and determine the highest price left over from those fields where there was a value.

2. Modified max(price) SQL query 

#### GitHub Troubleshooting
1. Worked with Ben to get "gitignore" on my files 

2. Moved out files that were too big to commit

---
## DAY 4: Tuesday (Week 2)

#### Work in Progress Feedback 
Got positive feedback from my presentation on Thursday.  No major change in course; just planning on closing out queries and presenting for this week.

#### Work towards milestone 1: Determine all the queries I will be doing in R
Decided to replicate all the SQL queries I did in SQL in R as well.  Complete, except for "like"/"contains" operator.

#### Work towards milestone 2: Finish Data Camp training for R
Did not get as far as I wanted here.

#### Work towards milestone 3: Come up with narrative for presentation & screenshots of tables/code
Spent more time formatting READme in this sprint. Goal for presentation is to use imagery, summarize the data table findings, and then show a side-by-side split comparison of SQL and R for code snippets for ~5 queries/asks of the table.

--- 

## DAY 5: Wednesday (Week 2)

### Project Highlights: The things I am most excited about in my project
Me
- Feeling more comfortable in R.
- During my queries in SQL, I was able to encounter "" values in SQL, and NA values in R.  This resulted in some additional querying and testing to the call to determine the answer to my question (in this case, the highest price wine in the database).

Peer Identified

- None

### Peer Repo Feedback 

*Here are the changes I am making to my repo structure for additional clarity* 
- Adding in plug-in to Repo so that R code will execute directly, rather than a separate file.

### Loop Quick Deep Dive
1. Use loops to avoid the DRY principle: Don't Repeat Yourself
2. Sample beginner loop that prints each year as a statement following the phrase "The year is":
`for (year in c(2010,2011,2012,2013,2014,2015)){
  print(paste("The year is", year))
}`
3. Sample beginner loop that prints odd numbers only:
`for (i in 1:10) {
  if (!i %% 2){
    next
  }
    print(i)
    }`
    
4. R-bloggesr.com says that you should avoid making loops in R because of vectorization. The latter allows for faster calculations using apply functions (lapply and sapply). Further information on these functions would be useful to understand.

5. Helpful link to understand basics of loops in Python: https://en.wikibooks.org/wiki/A_Beginner%27s_Python_Tutorial/Loops,_Conditionals

In [1]:
#SAMPLE LOOP FROM ONLINE EXAMPLE

#EXAMPLE 1
y = 1
if y == 1:
    print ("y still equals 1, I was just checking")

#EXAMPLE 2
print ("We will show the even numbers up to 20")
n = 1
while n <= 20:
    n = n + 1
    if n % 2 == 0:    
           print(n)
print("there, done.")

y still equals 1, I was just checking
We will show the even numbers up to 20
2
4
6
8
10
12
14
16
18
20
there, done.

In [3]:
#IF AND ELSE STATEMENTS
a = 100
if a > 5:
    print("This value is greater than 5.")
else:
    print("This value is not greater than 5.")

This value is greater than 5.

In [4]:
#SYNTAX FOR IF/ELIF/ELSE STATEMENTS

if {conditions}:
    {run this code}
elif {conditions}:
    {run this code}
elif {conditions}:
    {run this code}
else:
    {run this code}

SyntaxError: invalid syntax (<ipython-input-4-f3493c1479ef>, line 4)

In [5]:
a = 10
while a > 0:
    print(a)
    if a > 5:
        print("Big number!")
    elif a % 2 != 0:
        print("This is an odd number")
        print("It isn't greater than five, either")
    else:
        print("this number isn't greater than 5")
        print("nor is it odd")
        print("feeling special?")
    a = a - 1
    print("we just made 'a' one less than what it was!")
    print("and unless a is not greater than 0, we'll do the loop again.")
print("well, it seems as if 'a' is now no bigger than 0!")
print("the loop is now over, and without furthur ado, so is this program!")

10
Big number!
we just made 'a' one less than what it was!
and unless a is not greater than 0, we'll do the loop again.
9
Big number!
we just made 'a' one less than what it was!
and unless a is not greater than 0, we'll do the loop again.
8
Big number!
we just made 'a' one less than what it was!
and unless a is not greater than 0, we'll do the loop again.
7
Big number!
we just made 'a' one less than what it was!
and unless a is not greater than 0, we'll do the loop again.
6
Big number!
we just made 'a' one less than what it was!
and unless a is not greater than 0, we'll do the loop again.
5
This is an odd number
It isn't greater than five, either
we just made 'a' one less than what it was!
and unless a is not greater than 0, we'll do the loop again.
4
this number isn't greater than 5
nor is it odd
feeling special?
we just made 'a' one less than what it was!
and unless a is not greater than 0, we'll do the loop again.
3
This is an odd number
It isn't greater than five, either
we just made 'a' one less than what it was!
and unless a is not greater than 0, we'll do the loop again.
2
this number isn't greater than 5
nor is it odd
feeling special?
we just made 'a' one less than what it was!
and unless a is not greater than 0, we'll do the loop again.
1
This is an odd number
It isn't greater than five, either
we just made 'a' one less than what it was!
and unless a is not greater than 0, we'll do the loop again.
well, it seems as if 'a' is now no bigger than 0!
the loop is now over, and without furthur ado, so is this program!

In [6]:
a = 0
while a < 10:
    a = a + 1  #alternatively a += 1
    print(a)

1
2
3
4
5
6
7
8
9
10

In [7]:
#EXAMPLE
#Type this in and see what it does.
x = 10
while x != 0:
    print(x)
    x = x - 1
    print("Wow, we've counted x down, and now it equals", x)
print ("And now the loop has ended.")

10
Wow, we've counted x down, and now it equals 9
9
Wow, we've counted x down, and now it equals 8
8
Wow, we've counted x down, and now it equals 7
7
Wow, we've counted x down, and now it equals 6
6
Wow, we've counted x down, and now it equals 5
5
Wow, we've counted x down, and now it equals 4
4
Wow, we've counted x down, and now it equals 3
3
Wow, we've counted x down, and now it equals 2
2
Wow, we've counted x down, and now it equals 1
1
Wow, we've counted x down, and now it equals 0
And now the loop has ended.

## Day 6: Thursday (Week 2)
--- 

#### Things I didn't get to
*Here are some ideas that I didn't get to implement, but wanted to. I will be adding these to my roadmap table entry for this sprint as well.